### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by enkiluv** [Online-Election-System-Project/docs#3]
Requirement Gathering은 연관된 <B>Problem Statement</B>가 있어야 합니다. README 문서에 Problem Statement를 작성하기 바랍니다.

**Comment by Youhoseong** [comment]
작성 완료했습니다 교수님 !!

**Comment by enkiluv** [comment]
온라인 투표는 대리투표가 가능하고 개표(검표)에 조작이 가능하다고 의심받는 등 난점도 많습니다. 고객 관점에서 이런 문제에 대한 고려를 요구받는다면 초기 단계에서 어떦게 고려하고 반영해야할지 고민해보기 바랍니다.

**Comment by Youhoseong** [comment]
팀원들과 상의하여 해당 문제에 대해 고민해보고 답변드리겠습니다.

**Comment by enkiluv** [comment]
네, 모든 문제를 다 해결하라는 요구가 아니라 고객의 핵심 pain points가 무엇인지 비즈니스적 관점에서 초기에 고려하라는 것입니다. 이런 사항이 누락된채 기술적 분석만 마치고 개발을 하다보면 고객의 요구와 동떨어진 제품이나 서비스가 되기 쉽습니다.

**Comment by Youhoseong** [comment]
네! 신경써주셔서 감사합니다 교수님

**Comment by Youhoseong** [comment]
말씀해주신 문제에 대해 다뤄보았습니다.

1. 대리투표에 관한 문제
- 투표자는 투표 직전 관리자 화상 채팅을 통하여 신분증 확인 절차를 거친다

2. 조작에 관한 문제
- 개표 후 선거 결과에 대한 구체적인 데이터(세부 지역 별 유권자 수, 세부 지역 별 투표 현황)를 투표자들에게 시각성 좋게 제공하여 투표자들이 신뢰도를 높일 수 있도록 돕는다.

추가적으로 핵심 paint point를 생각해본 결과로, 투표 현황 데이터베이스를 구성하는데 유저 정보를 그대로 저장한다면, 누가 누구를 투표했는지 알 수 있는(비밀 투표 보장 실패) 경우가 생길 수 있는 문제가 있기에 이를 해쉬 알고리즘을 통해 변환된 유저 정보와 함께 저장하기로 하였습니다.

위와 같이 고민한 결과를 문서에도 반영하였습니다.  감사합니다.

**Comment by enkiluv** [comment]
좋은 의견입니다. 이처럼 진지한 고민이 개발하고자 하는 시스템의 비즈니스적 가치를 크게 높일 수 있습니다.

조금만 더 (고객의로서의) 의견을 말하자면, 이 단계에서는 화상채팅이나 해쉬와 같은 구체적 기술을 언급하기 보다 “부가 (이중) 인증을 요구한다”거나 “단 방향 익명화(A->X는 확인할 수 있지만 X->A는 확인 불가능하게)를 사용한다” 등과 같이 고객 관점에서의 용어를 사용하는 것이 좋습니다.
구체적 기술 선택은 Sprint에서 정의하는 결정하기 바랍니다.

이제 이 이슈는 close해도 되겠습니다.

--김명호

**Comment by enkiluv** [comment]
Issue closed.
